root: true
env:
  es2021: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "@stylistic"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "htmlacademy/node"

rules:
 "@stylistic/object-curly-spacing": ["error", "always"]
