# Категории
## Получить список предложений
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###

## Создать предложение
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Новая квартира в центре",
  "description": "Просторная квартира с видом на парк",
  "createdDate": "2024-02-07T10:00:00.000Z",
  "previewImage": "https://example.com/images/offer1.jpg",
  "images": [
    "https://example.com/images/offer1_1.jpg",
    "https://example.com/images/offer1_2.jpg"
  ],
  "type": "Buy",
  "price": 12000,
  "userId": "507f1f77bcf86cd799439011",
  "city": "Paris",
  "isPremium": true,
  "isFavorite": false,
  "roomsCount": 3,
  "commentsCount": 0,
  "visitorsCount": 0,
  "housingType": "Apartment",
  "coordinates": {
    "latitude": 48.8566,
    "longitude": 2.3522
  },
  "amenities": ["Workspace", "LaptopFriendly", "AirConditioning"],
  "rating": 4.5
}
###

# Получить предложение по идентификатору
GET http://localhost:4000/offers/62711a50b0e24a624d49ffdc HTTP/1.1

###


## Получить список предложений
GET http://localhost:4000/offers HTTP/1.1

###

## Обновить предложение по идентификатору

PATCH  http://localhost:4000/offers/62825028a75295825778ac80 HTTP/1.1
Content-Type: application/json

{
  "title": "Обновлённое название квартиры",
  "description": "Обновлённое описание квартиры",
  "price": 15000
}

###
## Удалить предложение по идентификатору

DELETE http://localhost:4000/offers/62825028a75295825778ac80 HTTP/1.1

###


## Список комментариев определённого предложения

GET http://localhost:4000/offers/65258514a30fc6ef77c0edfe/comments?limit=10 HTTP/1.1

###


## Создание комментария для предложения
POST http://localhost:4000/offers/65258514a30fc6ef77c0edfe/comments HTTP/1.1
Content-Type: application/json
{
  "text": "Отличное предложение, очень понравилось!",
  "offerId": "65258514a30fc6ef77c0edfe",
  "userId": "507f1f77bcf86cd799439011"
}
